### ISSUE TITLE
Error on Python 3.11

### ISSUE THREAD

**Issue by sawyerwtf** [lionrocker/solo-chess-solver#1]
```
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\solo-chess-solver-main\solo-chess-solver-main\main.py", line 14, in <module>
    pieceStr, squareStr = input().split(" ")
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```
Running within a terminal on Windows 11 with a fresh install of Python 3.11

**Comment by leonrode** [comment]
Hi @sawyerwtf,

That error arises when you've inputted the pieces incorrectly. Instead of inputting something like
```
Ne4
```

input
```
N e4
```

P.S. please clone the latest version as an extra print statement has just been removed.
